[package]
name = "yt-rss"
version = "0.2.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
cached = "0.43.0"
chrono = "0.4.31"
clap = { version = "4.4.18", features = ["derive"] }
feed-rs = "1.3.0"
regex = "1.8.1"
reqwest = { version = "0.11.17", features = ["blocking"] }
rss = "2.0.7"